version: 2.1

orbs:
  python: circleci/python@0.2.1

jobs:
  build-and-test:
    docker:
      - image: cimg/python:3.8.9
    steps:
      - checkout
      - python/load-cache
      - run:
          name: Install Python deps in a venv
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pip install -r requirements.txt
            kedro install
      - python/save-cache
      - run:
          command: |
            . venv/bin/activate
            kedro test --cov-report=xml:"./docs/coverage/coverage.xml"
          name: Test
      - store_artifacts:
          path: build/dist/ 
          destination: tr1
      - store_test_results:
          path: docs/coverage/

workflows:
  main:
    jobs:
      - build-and-test
