version: 2.1

orbs:
  python: circleci/python@0.2.1
  shiftleft: shiftleft/shiftleft@1.0

jobs:
  build-and-test:
    docker:
      - image: cimg/python:3.8.9
    steps:
      - checkout
      - python/load-cache
      - run:
          name: Install Python deps in a venv
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pip install -r requirements.txt
            kedro install
      - python/save-cache
      - run:
          command: |
            . venv/bin/activate
            kedro test \
              --junitxml="docs/coverage/test.xml" \
              --cov-report=html:"docs/html/"
          name: Test
      - run:
          command: |
            . venv/bin/activate
            kedro package
          name: Build egg & wheel
      - store_artifacts:
          path: src/dist/ 
          destination: tr1
      - store_artifacts:
          path: docs/html/
          destination: coverage
      - store_test_results:
          path: docs/coverage/

workflows:
  main:
    jobs:
      - build-and-test
  workflow:
    jobs:
      - shiftleft/analyze:
          app: kedro_ge 
          target: src
          language: python
